language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install selenium
# command to run tests
# command to run tests
script: pytest test_contributors.py
before_script: cd staging
 - pip install helpers
env:
  global:
    - secure: RzFfJA0NjkWnVqyfkW/Vnvwfn8ZqkH9XNvZOdXhkU1ZmIjuMYMDBkTJjaAknU++X2xX5RHOK3aW8DJmZ/hAXV9UUXT/ulYr7xErooMvPZ8pDCEpbDXKDqnr2XzVZAcicUdcK73IMzw0EDyTCJh/2KFphxXspI3VcclJOh7yxQNFHuK+khsLtEPxwJWeNz32ZsnxuKJOSfHTK0DQWwx3Xxfoz9gIfLm5nYbUL7DGjm2Tc6Jy0If2aPRZwnSpBxQ6arEw4kbFvbHXvv5q6Gd8nCzZM4dCqPNY9r/cKvwUapPXa700HLhs8gacmZw6hMgctxb8OAybd32ZTLTZfZMnAIOYweLsEqajz27Q9q/4yi71HvC0hbRQr+EUzuU60vmPv6UcWqAhP7O+4w4ze67UvKnaGjDA0aqWw/l5mLrbVkGuUVm3+JZamLZixkkU4ItkgHptsGn7YSw0CDdJb7GWXw4FqZ0uK2iLwe6wUGDkHs+qbt5HvsKlDfN9HzIKNedC8kCT+/+m4ywmDDdSjjQ9X6gP4d7f++Yx5LAY8kTmoLNNwWgABGWNP2EVnRtinmmYEWQINYv8H36vVPgI70oh0RDH4H8KyJu9EldvWA7GXwWdCReXfBPgq425KPCiNB3lVmxyII53aC8WEB/agbnnRJM7cCj/i4Tyakw8WiZPB6QQ=

   
