language: python

sudo: enabled
# command to install dependencies


   #   browser: Chrome
    #  browser_version: "61.0"
     # os: Windows
      #os_version: "10"
      #resolution: 2048x1536

install:
  - pip install selenium
  - gem install travis
 
 env:
  - DRIVER: webdriver.Remote(command_executor, desired_capabilities=DESIRED_CAP) 
  #- cp settings/travis-local.py settings/local.py
  
 
# command to run tests
script: pytest test_contributors.py
before_script: cd staging
 - pip install helpers
 
#Test to start travis




    
   
