language: python

sudo: enabled
# command to install dependencies

travis encrypt USERNAME_ONE = "osframeworktesting+selenium@gmail.com"

travis encrypt USERNAME_TWO = "osframeworktesting+ghost2@gmail.com"
   
travis encrypt PASSWORD = '"Repr0duce!"'
        
travis encrypt DRIVER = webdriver.Remote(
command_executor='http://osfselenium1:9asHrZGoyk7Tesx9agX5@hub.browserstack.com:80/wd/hub',
desired_capabilities=DESIRED_CAP)

install:
  - pip install selenium
  - gem install travis
  #- cp settings/travis-local.py settings/local.py
  
 
# command to run tests
script: pytest test_contributors.py

before_script: cd staging
 pip install helpers
 #Test


    
   
