language: python
python:
- '3.6'
sudo: false
env:
  global:
  - PROJECT_DIR="$PWD"
  - DRIVER="Remote"
  - secure: gAqXfDSBCvLz0SBptoStFoa5u3fhkjxKdJJtcIg+sO44d4sVDfZ6qhm5Qbz01JzvKBhqioQUddMWlDx+Khp3yIB9o0y5kjNYy+qNjB1O93ngTkihiYh1ty1sIHFYTr5mKEgxk8dZANsQlUFo4eJAvUNMgAmiN2r7BnQKAPgWO5Zb7FUMsh2pk8Hlecq6Gk6qjvgN7VlQDnMTcFdB/BifODQ1cKNM5Salg+st9UV16pADy9OBnFkFkETZPMG1pKJmRw4qTBSY/QHIehQhtqpFMpo7lMoCke6J2tXW9dCeR3lSWtLAu7izeDlb9y9U+Ys6JdikgDot2zF0yVqD4YfhNR7bvTYEo+13CHwjcF+3U1+7ORL8JTAiI6pCi6MKrTCpLPgO7KDcS5erNgE0xNiKyiWOIi42MtFv2C1h/TWc9NWqHTiGM5kyAZteT8h9d7tbCPoal1UiKYu5x2UV4HpUOKvHCtMrJUjnGlM9aQTOYc/o9QKRSUs+G+KKcrmnMYpFIrntlAQgkLg21sM8WDIoQgi8hmUlmL3K3MKvx/51f3JIxsuTAMyvG5drVEpwkCM2VOjfxy+8sn1pV3K6GDThKONpXVwniL0tsmPDRidiJBNsTwIvhOFvlzyd3zbfSfAZGc7WMyDT1GwTRu4OZI0jQB4umYsxMdfeFbDY+TSZH3I=
notifications:
  flowdock:
    secure: h98OMImn7qLMPLBbpbrjlgkzmPP+1l55beA0rY1hh7pj8eXx7qEKGpdSFREGf+yyqU9xSf6aRquVQMnJeP8stDoACwSHEsCroZ6Aojp7/l+4184viqKDHypkbntsWVw+4b547tNUTkp12/yV1JZieUP7bobc6+7pksqksnmLhhlD+L+YAgXCJC3L2cFTh1mL6jHVtpgvTBf9lOWQnFnNTQy64NMZ288k9gqbRW0KKqSxaFtdS7T1Z62jH5gRUUtGAruza7tCLCmu/M/r9XDfmYsETebr6eKdWWk4qH37f0OCAgzrF3HbVkTMVUstH+7Lq4G1lJdUJAyuIS8tXhYAodDZrQB6qkw6IcWbBHrf6oO4fwvcQYbN05oAtbo5MmX4AQQnkoQbYmmYg14WlQ7LEHmWGLYwWo6qlX921IaJeYQtl5ESFKmKj4ckqz/nxjsXdy7yj7y4Zvr4kQCJg9TrSgeb1g3jlrywN8pWRf9abZ58WkJZruspx9IuZnnUVGd33rM2UpL5Bf8/SyFjiBW5tKVrKZO2vtsfx2O+5n7YafGkPp1iobK9V7AdBwezyWMh971o7q96RmCANJPnGq3scNV//gQbyXmVLMG8pdvDyTWs38ane/5PmjdmsNLmTKx5uMdja9cJ+9Yls/JGKVv58U5A3JR/R7sW89Em9fejo8U=
install:
- cd $PROJECT_DIR
- travis_retry pip install --upgrade pip
- travis_retry pip install invoke==0.13.0
- travis_retry invoke requirements
jobs:
  include:
  - stage: Prod smoke tests
    if: branch = master
    env:
    - DOMAIN='prod'
    - PREFERRED_NODE='ucrdq'
    script: invoke test_travis_on_prod
  - if: branch != master
    env: TEST_BUILD="chrome"
  - if: branch != master
    env: TEST_BUILD="firefox"
  - if: branch != master
    env: TEST_BUILD="edge"
script:
- invoke test_travis_$TEST_BUILD
