language: python

sudo: enabled
# command to install dependencies

install:
  - pip install selenium
  - gem install travis
  - cp settings/travis-local.py settings/local.py
  
 
# command to run tests
script: pytest test_landing_page.py

before_script: cd staging
 pip install helpers
 #Test


    
   
