language: python

sudo: enabled
# command to install dependencies
install:
  - pip install selenium
  #- pip install -r requirements.txt
# command to run tests
script: pytest login1.py

before_script: cd Staging


    
   
