language: python
python:
  - '3.6'
sudo: false
env:
  global:
  - PROJECT_DIR="$PWD"
  - DRIVER="Remote"
  
install:
  - cd $PROJECT_DIR
  - travis_retry pip install --upgrade pip
  - travis_retry pip install invoke==0.13.0
  - travis_retry invoke requirements
jobs:
  include:
    - stage: "Prod smoke tests"
      if: branch = master
      env:
        - DOMAIN='prod'
        - PREFERRED_NODE='ucrdq'
      script: invoke test_travis_on_prod
    - if: branch != master
      env: TEST_BUILD="chrome"
    - if: branch != master
      env: TEST_BUILD="firefox"
    - if: branch != master
      env: TEST_BUILD="edge"
script:
  - invoke test_travis_$TEST_BUILD
