language: python

sudo: enabled
# command to install dependencies
install:
  - pip install selenium
  - cp settings/local-travis.py settings/local.py
  
 
# command to run tests
script: pytest test_contributors.py

before_script: cd staging
 pip install helpers
 #Test


    
   
