language: python

sudo: enabled
# command to install dependencies
install:
  - pip install selenium
  #- pip install -r requirements.txt
# command to run tests
script: pytest

addons:
  browserstack:
    username: "shikhadubey1"
    access_key: "Mhtt1XkQq18k8nqQzsqn"
    
    
# Input capabilities
caps = Selenium::WebDriver::Remote::Capabilities.new
caps['browserstack.local'] = 'true'
caps['browserstack.localIdentifier'] = ENV['BROWSERSTACK_LOCAL_IDENTIFIER']
# Add other capabilities like browser name, version and os name, version
...

driver = Selenium::WebDriver.for(:remote,
  :url => "http://USERNAME:ACCESS_KEY@hub-cloud.browserstack.com/wd/hub",
  :desired_capabilities => caps)
