name: osf-selenium-tests CI

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - 'release/*'
      - 'hotfix/*'
      - 'feature/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DRIVER: "Remote"
  DOMAIN: test

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install invoke==0.13.0
          pip install flake8
          invoke requirements
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  smoke_test:
    name: Prod smoke tests (${{ matrix.browser }})
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1  # run in series
      matrix:
        browser: [chrome, firefox, -edge]
    steps:
      - name: run smoke tests
        if: branch == master
        env:
          DOMAIN: prod
          PREFERRED_NODE: ra4bf
          TEST_BUILD: ${{ matrix.browser }}
        run: |
          invoke test_travis_on_prod

  staging_test:
    name: Staging tests (${{ matrix.browser }}) part ${{ matrix.partition }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1  # run in series
      matrix:
        browser: [chrome, firefox, -edge]
        partition: [one, two]
    steps:
      - name: run staging tests
        if: branch != master
        env:
          TEST_BUILD: ${{ matrix.browser }}
        run: |
          invoke test_travis_on_prod_part_${{ matrix.partition }}
